/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HandoffsRouteImport } from './routes/handoffs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiTerminalStreamRouteImport } from './routes/api/terminal-stream'
import { Route as ApiTerminalResizeRouteImport } from './routes/api/terminal-resize'
import { Route as ApiTerminalInputRouteImport } from './routes/api/terminal-input'
import { Route as ApiTerminalCloseRouteImport } from './routes/api/terminal-close'
import { Route as ApiStartHermesRouteImport } from './routes/api/start-hermes'
import { Route as ApiStartAgentRouteImport } from './routes/api/start-agent'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSessionStatusRouteImport } from './routes/api/session-status'
import { Route as ApiSendStreamRouteImport } from './routes/api/send-stream'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiHermesJobsRouteImport } from './routes/api/hermes-jobs'
import { Route as ApiHermesConfigRouteImport } from './routes/api/hermes-config'
import { Route as ApiGatewayStatusRouteImport } from './routes/api/gateway-status'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiContextUsageRouteImport } from './routes/api/context-usage'
import { Route as ApiConnectionStatusRouteImport } from './routes/api/connection-status'
import { Route as ApiChatEventsRouteImport } from './routes/api/chat-events'
import { Route as ApiAuthCheckRouteImport } from './routes/api/auth-check'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiSessionsSendRouteImport } from './routes/api/sessions/send'
import { Route as ApiPaperclipRouteNextRouteImport } from './routes/api/paperclip/route-next'
import { Route as ApiPaperclipResumeMissionRouteImport } from './routes/api/paperclip/resume-mission'
import { Route as ApiPaperclipProjectsRouteImport } from './routes/api/paperclip/projects'
import { Route as ApiPaperclipMissionsRouteImport } from './routes/api/paperclip/missions'
import { Route as ApiPaperclipLaunchRoleRouteImport } from './routes/api/paperclip/launch-role'
import { Route as ApiPaperclipHandoffsRouteImport } from './routes/api/paperclip/handoffs'
import { Route as ApiPaperclipCompanyRouteImport } from './routes/api/paperclip/company'
import { Route as ApiPaperclipApprovalsRouteImport } from './routes/api/paperclip/approvals'
import { Route as ApiOauthPollTokenRouteImport } from './routes/api/oauth.poll-token'
import { Route as ApiOauthDeviceCodeRouteImport } from './routes/api/oauth.device-code'
import { Route as ApiMemoryWriteRouteImport } from './routes/api/memory/write'
import { Route as ApiMemorySearchRouteImport } from './routes/api/memory/search'
import { Route as ApiMemoryReadRouteImport } from './routes/api/memory/read'
import { Route as ApiMemoryListRouteImport } from './routes/api/memory/list'
import { Route as ApiHermesJobsJobIdRouteImport } from './routes/api/hermes-jobs.$jobId'
import { Route as ApiSessionsSessionKeyStatusRouteImport } from './routes/api/sessions/$sessionKey.status'
import { Route as ApiPaperclipProjectsProjectIdRouteImport } from './routes/api/paperclip/projects.$projectId'
import { Route as ApiPaperclipMissionsMissionIdRouteImport } from './routes/api/paperclip/missions.$missionId'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffsRoute = HandoffsRouteImport.update({
  id: '/handoffs',
  path: '/handoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalStreamRoute = ApiTerminalStreamRouteImport.update({
  id: '/api/terminal-stream',
  path: '/api/terminal-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalResizeRoute = ApiTerminalResizeRouteImport.update({
  id: '/api/terminal-resize',
  path: '/api/terminal-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalInputRoute = ApiTerminalInputRouteImport.update({
  id: '/api/terminal-input',
  path: '/api/terminal-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalCloseRoute = ApiTerminalCloseRouteImport.update({
  id: '/api/terminal-close',
  path: '/api/terminal-close',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartHermesRoute = ApiStartHermesRouteImport.update({
  id: '/api/start-hermes',
  path: '/api/start-hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartAgentRoute = ApiStartAgentRouteImport.update({
  id: '/api/start-agent',
  path: '/api/start-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionStatusRoute = ApiSessionStatusRouteImport.update({
  id: '/api/session-status',
  path: '/api/session-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendStreamRoute = ApiSendStreamRouteImport.update({
  id: '/api/send-stream',
  path: '/api/send-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJobsRoute = ApiHermesJobsRouteImport.update({
  id: '/api/hermes-jobs',
  path: '/api/hermes-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesConfigRoute = ApiHermesConfigRouteImport.update({
  id: '/api/hermes-config',
  path: '/api/hermes-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayStatusRoute = ApiGatewayStatusRouteImport.update({
  id: '/api/gateway-status',
  path: '/api/gateway-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextUsageRoute = ApiContextUsageRouteImport.update({
  id: '/api/context-usage',
  path: '/api/context-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionStatusRoute = ApiConnectionStatusRouteImport.update({
  id: '/api/connection-status',
  path: '/api/connection-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatEventsRoute = ApiChatEventsRouteImport.update({
  id: '/api/chat-events',
  path: '/api/chat-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCheckRoute = ApiAuthCheckRouteImport.update({
  id: '/api/auth-check',
  path: '/api/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSendRoute = ApiSessionsSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiPaperclipRouteNextRoute = ApiPaperclipRouteNextRouteImport.update({
  id: '/api/paperclip/route-next',
  path: '/api/paperclip/route-next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperclipResumeMissionRoute =
  ApiPaperclipResumeMissionRouteImport.update({
    id: '/api/paperclip/resume-mission',
    path: '/api/paperclip/resume-mission',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaperclipProjectsRoute = ApiPaperclipProjectsRouteImport.update({
  id: '/api/paperclip/projects',
  path: '/api/paperclip/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperclipMissionsRoute = ApiPaperclipMissionsRouteImport.update({
  id: '/api/paperclip/missions',
  path: '/api/paperclip/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperclipLaunchRoleRoute = ApiPaperclipLaunchRoleRouteImport.update({
  id: '/api/paperclip/launch-role',
  path: '/api/paperclip/launch-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperclipHandoffsRoute = ApiPaperclipHandoffsRouteImport.update({
  id: '/api/paperclip/handoffs',
  path: '/api/paperclip/handoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperclipCompanyRoute = ApiPaperclipCompanyRouteImport.update({
  id: '/api/paperclip/company',
  path: '/api/paperclip/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperclipApprovalsRoute = ApiPaperclipApprovalsRouteImport.update({
  id: '/api/paperclip/approvals',
  path: '/api/paperclip/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthPollTokenRoute = ApiOauthPollTokenRouteImport.update({
  id: '/api/oauth/poll-token',
  path: '/api/oauth/poll-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthDeviceCodeRoute = ApiOauthDeviceCodeRouteImport.update({
  id: '/api/oauth/device-code',
  path: '/api/oauth/device-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryWriteRoute = ApiMemoryWriteRouteImport.update({
  id: '/api/memory/write',
  path: '/api/memory/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemorySearchRoute = ApiMemorySearchRouteImport.update({
  id: '/api/memory/search',
  path: '/api/memory/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryReadRoute = ApiMemoryReadRouteImport.update({
  id: '/api/memory/read',
  path: '/api/memory/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryListRoute = ApiMemoryListRouteImport.update({
  id: '/api/memory/list',
  path: '/api/memory/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJobsJobIdRoute = ApiHermesJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiHermesJobsRoute,
} as any)
const ApiSessionsSessionKeyStatusRoute =
  ApiSessionsSessionKeyStatusRouteImport.update({
    id: '/$sessionKey/status',
    path: '/$sessionKey/status',
    getParentRoute: () => ApiSessionsRoute,
  } as any)
const ApiPaperclipProjectsProjectIdRoute =
  ApiPaperclipProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => ApiPaperclipProjectsRoute,
  } as any)
const ApiPaperclipMissionsMissionIdRoute =
  ApiPaperclipMissionsMissionIdRouteImport.update({
    id: '/$missionId',
    path: '/$missionId',
    getParentRoute: () => ApiPaperclipMissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/handoffs': typeof HandoffsRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/missions': typeof MissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRoute
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat/': typeof ChatIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/paperclip/approvals': typeof ApiPaperclipApprovalsRoute
  '/api/paperclip/company': typeof ApiPaperclipCompanyRoute
  '/api/paperclip/handoffs': typeof ApiPaperclipHandoffsRoute
  '/api/paperclip/launch-role': typeof ApiPaperclipLaunchRoleRoute
  '/api/paperclip/missions': typeof ApiPaperclipMissionsRouteWithChildren
  '/api/paperclip/projects': typeof ApiPaperclipProjectsRouteWithChildren
  '/api/paperclip/resume-mission': typeof ApiPaperclipResumeMissionRoute
  '/api/paperclip/route-next': typeof ApiPaperclipRouteNextRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/paperclip/missions/$missionId': typeof ApiPaperclipMissionsMissionIdRoute
  '/api/paperclip/projects/$projectId': typeof ApiPaperclipProjectsProjectIdRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/handoffs': typeof HandoffsRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/missions': typeof MissionsRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRoute
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat': typeof ChatIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/paperclip/approvals': typeof ApiPaperclipApprovalsRoute
  '/api/paperclip/company': typeof ApiPaperclipCompanyRoute
  '/api/paperclip/handoffs': typeof ApiPaperclipHandoffsRoute
  '/api/paperclip/launch-role': typeof ApiPaperclipLaunchRoleRoute
  '/api/paperclip/missions': typeof ApiPaperclipMissionsRouteWithChildren
  '/api/paperclip/projects': typeof ApiPaperclipProjectsRouteWithChildren
  '/api/paperclip/resume-mission': typeof ApiPaperclipResumeMissionRoute
  '/api/paperclip/route-next': typeof ApiPaperclipRouteNextRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/paperclip/missions/$missionId': typeof ApiPaperclipMissionsMissionIdRoute
  '/api/paperclip/projects/$projectId': typeof ApiPaperclipProjectsProjectIdRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/handoffs': typeof HandoffsRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/missions': typeof MissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRoute
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat/': typeof ChatIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/paperclip/approvals': typeof ApiPaperclipApprovalsRoute
  '/api/paperclip/company': typeof ApiPaperclipCompanyRoute
  '/api/paperclip/handoffs': typeof ApiPaperclipHandoffsRoute
  '/api/paperclip/launch-role': typeof ApiPaperclipLaunchRoleRoute
  '/api/paperclip/missions': typeof ApiPaperclipMissionsRouteWithChildren
  '/api/paperclip/projects': typeof ApiPaperclipProjectsRouteWithChildren
  '/api/paperclip/resume-mission': typeof ApiPaperclipResumeMissionRoute
  '/api/paperclip/route-next': typeof ApiPaperclipRouteNextRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/paperclip/missions/$missionId': typeof ApiPaperclipMissionsMissionIdRoute
  '/api/paperclip/projects/$projectId': typeof ApiPaperclipProjectsProjectIdRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/approvals'
    | '/dashboard'
    | '/files'
    | '/handoffs'
    | '/jobs'
    | '/memory'
    | '/missions'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/history'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/projects/$projectId'
    | '/settings/providers'
    | '/chat/'
    | '/projects/'
    | '/settings/'
    | '/api/hermes-jobs/$jobId'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/paperclip/approvals'
    | '/api/paperclip/company'
    | '/api/paperclip/handoffs'
    | '/api/paperclip/launch-role'
    | '/api/paperclip/missions'
    | '/api/paperclip/projects'
    | '/api/paperclip/resume-mission'
    | '/api/paperclip/route-next'
    | '/api/sessions/send'
    | '/api/paperclip/missions/$missionId'
    | '/api/paperclip/projects/$projectId'
    | '/api/sessions/$sessionKey/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/approvals'
    | '/dashboard'
    | '/files'
    | '/handoffs'
    | '/jobs'
    | '/memory'
    | '/missions'
    | '/skills'
    | '/terminal'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/history'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/projects/$projectId'
    | '/settings/providers'
    | '/chat'
    | '/projects'
    | '/settings'
    | '/api/hermes-jobs/$jobId'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/paperclip/approvals'
    | '/api/paperclip/company'
    | '/api/paperclip/handoffs'
    | '/api/paperclip/launch-role'
    | '/api/paperclip/missions'
    | '/api/paperclip/projects'
    | '/api/paperclip/resume-mission'
    | '/api/paperclip/route-next'
    | '/api/sessions/send'
    | '/api/paperclip/missions/$missionId'
    | '/api/paperclip/projects/$projectId'
    | '/api/sessions/$sessionKey/status'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/approvals'
    | '/dashboard'
    | '/files'
    | '/handoffs'
    | '/jobs'
    | '/memory'
    | '/missions'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/history'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/projects/$projectId'
    | '/settings/providers'
    | '/chat/'
    | '/projects/'
    | '/settings/'
    | '/api/hermes-jobs/$jobId'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/paperclip/approvals'
    | '/api/paperclip/company'
    | '/api/paperclip/handoffs'
    | '/api/paperclip/launch-role'
    | '/api/paperclip/missions'
    | '/api/paperclip/projects'
    | '/api/paperclip/resume-mission'
    | '/api/paperclip/route-next'
    | '/api/sessions/send'
    | '/api/paperclip/missions/$missionId'
    | '/api/paperclip/projects/$projectId'
    | '/api/sessions/$sessionKey/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApprovalsRoute: typeof ApprovalsRoute
  DashboardRoute: typeof DashboardRoute
  FilesRoute: typeof FilesRoute
  HandoffsRoute: typeof HandoffsRoute
  JobsRoute: typeof JobsRoute
  MemoryRoute: typeof MemoryRoute
  MissionsRoute: typeof MissionsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
  TerminalRoute: typeof TerminalRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiAuthCheckRoute: typeof ApiAuthCheckRoute
  ApiChatEventsRoute: typeof ApiChatEventsRoute
  ApiConnectionStatusRoute: typeof ApiConnectionStatusRoute
  ApiContextUsageRoute: typeof ApiContextUsageRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiGatewayStatusRoute: typeof ApiGatewayStatusRoute
  ApiHermesConfigRoute: typeof ApiHermesConfigRoute
  ApiHermesJobsRoute: typeof ApiHermesJobsRouteWithChildren
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSendStreamRoute: typeof ApiSendStreamRoute
  ApiSessionStatusRoute: typeof ApiSessionStatusRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiSkillsRoute: typeof ApiSkillsRoute
  ApiStartAgentRoute: typeof ApiStartAgentRoute
  ApiStartHermesRoute: typeof ApiStartHermesRoute
  ApiTerminalCloseRoute: typeof ApiTerminalCloseRoute
  ApiTerminalInputRoute: typeof ApiTerminalInputRoute
  ApiTerminalResizeRoute: typeof ApiTerminalResizeRoute
  ApiTerminalStreamRoute: typeof ApiTerminalStreamRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiMemoryListRoute: typeof ApiMemoryListRoute
  ApiMemoryReadRoute: typeof ApiMemoryReadRoute
  ApiMemorySearchRoute: typeof ApiMemorySearchRoute
  ApiMemoryWriteRoute: typeof ApiMemoryWriteRoute
  ApiOauthDeviceCodeRoute: typeof ApiOauthDeviceCodeRoute
  ApiOauthPollTokenRoute: typeof ApiOauthPollTokenRoute
  ApiPaperclipApprovalsRoute: typeof ApiPaperclipApprovalsRoute
  ApiPaperclipCompanyRoute: typeof ApiPaperclipCompanyRoute
  ApiPaperclipHandoffsRoute: typeof ApiPaperclipHandoffsRoute
  ApiPaperclipLaunchRoleRoute: typeof ApiPaperclipLaunchRoleRoute
  ApiPaperclipMissionsRoute: typeof ApiPaperclipMissionsRouteWithChildren
  ApiPaperclipProjectsRoute: typeof ApiPaperclipProjectsRouteWithChildren
  ApiPaperclipResumeMissionRoute: typeof ApiPaperclipResumeMissionRoute
  ApiPaperclipRouteNextRoute: typeof ApiPaperclipRouteNextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoffs': {
      id: '/handoffs'
      path: '/handoffs'
      fullPath: '/handoffs'
      preLoaderRoute: typeof HandoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-stream': {
      id: '/api/terminal-stream'
      path: '/api/terminal-stream'
      fullPath: '/api/terminal-stream'
      preLoaderRoute: typeof ApiTerminalStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-resize': {
      id: '/api/terminal-resize'
      path: '/api/terminal-resize'
      fullPath: '/api/terminal-resize'
      preLoaderRoute: typeof ApiTerminalResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-input': {
      id: '/api/terminal-input'
      path: '/api/terminal-input'
      fullPath: '/api/terminal-input'
      preLoaderRoute: typeof ApiTerminalInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-close': {
      id: '/api/terminal-close'
      path: '/api/terminal-close'
      fullPath: '/api/terminal-close'
      preLoaderRoute: typeof ApiTerminalCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/start-hermes': {
      id: '/api/start-hermes'
      path: '/api/start-hermes'
      fullPath: '/api/start-hermes'
      preLoaderRoute: typeof ApiStartHermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/start-agent': {
      id: '/api/start-agent'
      path: '/api/start-agent'
      fullPath: '/api/start-agent'
      preLoaderRoute: typeof ApiStartAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-status': {
      id: '/api/session-status'
      path: '/api/session-status'
      fullPath: '/api/session-status'
      preLoaderRoute: typeof ApiSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-stream': {
      id: '/api/send-stream'
      path: '/api/send-stream'
      fullPath: '/api/send-stream'
      preLoaderRoute: typeof ApiSendStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-jobs': {
      id: '/api/hermes-jobs'
      path: '/api/hermes-jobs'
      fullPath: '/api/hermes-jobs'
      preLoaderRoute: typeof ApiHermesJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-config': {
      id: '/api/hermes-config'
      path: '/api/hermes-config'
      fullPath: '/api/hermes-config'
      preLoaderRoute: typeof ApiHermesConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway-status': {
      id: '/api/gateway-status'
      path: '/api/gateway-status'
      fullPath: '/api/gateway-status'
      preLoaderRoute: typeof ApiGatewayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context-usage': {
      id: '/api/context-usage'
      path: '/api/context-usage'
      fullPath: '/api/context-usage'
      preLoaderRoute: typeof ApiContextUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connection-status': {
      id: '/api/connection-status'
      path: '/api/connection-status'
      fullPath: '/api/connection-status'
      preLoaderRoute: typeof ApiConnectionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-events': {
      id: '/api/chat-events'
      path: '/api/chat-events'
      fullPath: '/api/chat-events'
      preLoaderRoute: typeof ApiChatEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-check': {
      id: '/api/auth-check'
      path: '/api/auth-check'
      fullPath: '/api/auth-check'
      preLoaderRoute: typeof ApiAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/send': {
      id: '/api/sessions/send'
      path: '/send'
      fullPath: '/api/sessions/send'
      preLoaderRoute: typeof ApiSessionsSendRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/paperclip/route-next': {
      id: '/api/paperclip/route-next'
      path: '/api/paperclip/route-next'
      fullPath: '/api/paperclip/route-next'
      preLoaderRoute: typeof ApiPaperclipRouteNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paperclip/resume-mission': {
      id: '/api/paperclip/resume-mission'
      path: '/api/paperclip/resume-mission'
      fullPath: '/api/paperclip/resume-mission'
      preLoaderRoute: typeof ApiPaperclipResumeMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paperclip/projects': {
      id: '/api/paperclip/projects'
      path: '/api/paperclip/projects'
      fullPath: '/api/paperclip/projects'
      preLoaderRoute: typeof ApiPaperclipProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paperclip/missions': {
      id: '/api/paperclip/missions'
      path: '/api/paperclip/missions'
      fullPath: '/api/paperclip/missions'
      preLoaderRoute: typeof ApiPaperclipMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paperclip/launch-role': {
      id: '/api/paperclip/launch-role'
      path: '/api/paperclip/launch-role'
      fullPath: '/api/paperclip/launch-role'
      preLoaderRoute: typeof ApiPaperclipLaunchRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paperclip/handoffs': {
      id: '/api/paperclip/handoffs'
      path: '/api/paperclip/handoffs'
      fullPath: '/api/paperclip/handoffs'
      preLoaderRoute: typeof ApiPaperclipHandoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paperclip/company': {
      id: '/api/paperclip/company'
      path: '/api/paperclip/company'
      fullPath: '/api/paperclip/company'
      preLoaderRoute: typeof ApiPaperclipCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paperclip/approvals': {
      id: '/api/paperclip/approvals'
      path: '/api/paperclip/approvals'
      fullPath: '/api/paperclip/approvals'
      preLoaderRoute: typeof ApiPaperclipApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/poll-token': {
      id: '/api/oauth/poll-token'
      path: '/api/oauth/poll-token'
      fullPath: '/api/oauth/poll-token'
      preLoaderRoute: typeof ApiOauthPollTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/device-code': {
      id: '/api/oauth/device-code'
      path: '/api/oauth/device-code'
      fullPath: '/api/oauth/device-code'
      preLoaderRoute: typeof ApiOauthDeviceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/write': {
      id: '/api/memory/write'
      path: '/api/memory/write'
      fullPath: '/api/memory/write'
      preLoaderRoute: typeof ApiMemoryWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/search': {
      id: '/api/memory/search'
      path: '/api/memory/search'
      fullPath: '/api/memory/search'
      preLoaderRoute: typeof ApiMemorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/read': {
      id: '/api/memory/read'
      path: '/api/memory/read'
      fullPath: '/api/memory/read'
      preLoaderRoute: typeof ApiMemoryReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/list': {
      id: '/api/memory/list'
      path: '/api/memory/list'
      fullPath: '/api/memory/list'
      preLoaderRoute: typeof ApiMemoryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-jobs/$jobId': {
      id: '/api/hermes-jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/hermes-jobs/$jobId'
      preLoaderRoute: typeof ApiHermesJobsJobIdRouteImport
      parentRoute: typeof ApiHermesJobsRoute
    }
    '/api/sessions/$sessionKey/status': {
      id: '/api/sessions/$sessionKey/status'
      path: '/$sessionKey/status'
      fullPath: '/api/sessions/$sessionKey/status'
      preLoaderRoute: typeof ApiSessionsSessionKeyStatusRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/paperclip/projects/$projectId': {
      id: '/api/paperclip/projects/$projectId'
      path: '/$projectId'
      fullPath: '/api/paperclip/projects/$projectId'
      preLoaderRoute: typeof ApiPaperclipProjectsProjectIdRouteImport
      parentRoute: typeof ApiPaperclipProjectsRoute
    }
    '/api/paperclip/missions/$missionId': {
      id: '/api/paperclip/missions/$missionId'
      path: '/$missionId'
      fullPath: '/api/paperclip/missions/$missionId'
      preLoaderRoute: typeof ApiPaperclipMissionsMissionIdRouteImport
      parentRoute: typeof ApiPaperclipMissionsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiHermesJobsRouteChildren {
  ApiHermesJobsJobIdRoute: typeof ApiHermesJobsJobIdRoute
}

const ApiHermesJobsRouteChildren: ApiHermesJobsRouteChildren = {
  ApiHermesJobsJobIdRoute: ApiHermesJobsJobIdRoute,
}

const ApiHermesJobsRouteWithChildren = ApiHermesJobsRoute._addFileChildren(
  ApiHermesJobsRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsSendRoute: typeof ApiSessionsSendRoute
  ApiSessionsSessionKeyStatusRoute: typeof ApiSessionsSessionKeyStatusRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsSendRoute: ApiSessionsSendRoute,
  ApiSessionsSessionKeyStatusRoute: ApiSessionsSessionKeyStatusRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

interface ApiPaperclipMissionsRouteChildren {
  ApiPaperclipMissionsMissionIdRoute: typeof ApiPaperclipMissionsMissionIdRoute
}

const ApiPaperclipMissionsRouteChildren: ApiPaperclipMissionsRouteChildren = {
  ApiPaperclipMissionsMissionIdRoute: ApiPaperclipMissionsMissionIdRoute,
}

const ApiPaperclipMissionsRouteWithChildren =
  ApiPaperclipMissionsRoute._addFileChildren(ApiPaperclipMissionsRouteChildren)

interface ApiPaperclipProjectsRouteChildren {
  ApiPaperclipProjectsProjectIdRoute: typeof ApiPaperclipProjectsProjectIdRoute
}

const ApiPaperclipProjectsRouteChildren: ApiPaperclipProjectsRouteChildren = {
  ApiPaperclipProjectsProjectIdRoute: ApiPaperclipProjectsProjectIdRoute,
}

const ApiPaperclipProjectsRouteWithChildren =
  ApiPaperclipProjectsRoute._addFileChildren(ApiPaperclipProjectsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApprovalsRoute: ApprovalsRoute,
  DashboardRoute: DashboardRoute,
  FilesRoute: FilesRoute,
  HandoffsRoute: HandoffsRoute,
  JobsRoute: JobsRoute,
  MemoryRoute: MemoryRoute,
  MissionsRoute: MissionsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SkillsRoute: SkillsRoute,
  TerminalRoute: TerminalRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiAuthCheckRoute: ApiAuthCheckRoute,
  ApiChatEventsRoute: ApiChatEventsRoute,
  ApiConnectionStatusRoute: ApiConnectionStatusRoute,
  ApiContextUsageRoute: ApiContextUsageRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiGatewayStatusRoute: ApiGatewayStatusRoute,
  ApiHermesConfigRoute: ApiHermesConfigRoute,
  ApiHermesJobsRoute: ApiHermesJobsRouteWithChildren,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSendStreamRoute: ApiSendStreamRoute,
  ApiSessionStatusRoute: ApiSessionStatusRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiSkillsRoute: ApiSkillsRoute,
  ApiStartAgentRoute: ApiStartAgentRoute,
  ApiStartHermesRoute: ApiStartHermesRoute,
  ApiTerminalCloseRoute: ApiTerminalCloseRoute,
  ApiTerminalInputRoute: ApiTerminalInputRoute,
  ApiTerminalResizeRoute: ApiTerminalResizeRoute,
  ApiTerminalStreamRoute: ApiTerminalStreamRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiMemoryListRoute: ApiMemoryListRoute,
  ApiMemoryReadRoute: ApiMemoryReadRoute,
  ApiMemorySearchRoute: ApiMemorySearchRoute,
  ApiMemoryWriteRoute: ApiMemoryWriteRoute,
  ApiOauthDeviceCodeRoute: ApiOauthDeviceCodeRoute,
  ApiOauthPollTokenRoute: ApiOauthPollTokenRoute,
  ApiPaperclipApprovalsRoute: ApiPaperclipApprovalsRoute,
  ApiPaperclipCompanyRoute: ApiPaperclipCompanyRoute,
  ApiPaperclipHandoffsRoute: ApiPaperclipHandoffsRoute,
  ApiPaperclipLaunchRoleRoute: ApiPaperclipLaunchRoleRoute,
  ApiPaperclipMissionsRoute: ApiPaperclipMissionsRouteWithChildren,
  ApiPaperclipProjectsRoute: ApiPaperclipProjectsRouteWithChildren,
  ApiPaperclipResumeMissionRoute: ApiPaperclipResumeMissionRoute,
  ApiPaperclipRouteNextRoute: ApiPaperclipRouteNextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
